version: '3.1'

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    container_name: demo_api
    ports:
      - 3003:3000

  postgres:
    image: postgres
    container_name: demo_api_db
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
